### PR TITLE
Tree

### PR DESCRIPTION
**Pull request by MaevaLC**
Tree.py is supposed to be fully working now with any annotatedText.

Graph is just a scratch - to be deleted
Graph_anytree and Graph_treelib were test of the libs anytree and treelib and can also be deleted.

### CODE REVIEW

**Comment by dhmmasson** [comment]
@MaevaLC : 
I can't run Tree.py, the lib graphics is missing. 
I tried to do pip install graphics but it failed. If the lib is a single file ( e.g. http://mcsp.wartburg.edu/zelle/python/graphics.py ) add it to the repository

**Comment by dhmmasson** [comment]
In the code you don't need to have hauteur and longueur as global.
Similarly, you can change countOfParent to `def countOfParent(count, listeDependencyParent, indexWord):`  and remove the global compteur.

Almost everything is in english. 

The structure used are not very clear, it's quite hard to understand what are the elements listChildren 
maybe explicit something / somewhere. 
Could you use an object/dict rather that some anonymous indices ? Or maybe use const variables 
 with explicit names instead of 0, 1, 2...

**Comment by MaevaLC** [comment]
Tree has been completely rewritten, to make it clearer.
Graphics.py has been added to the repository.

**Comment by dhmmasson** [comment]
Well done !
I just made some small clean-ups ( check the diff of my last commit )

I have now just one question : on the X axis all nodes are drawn relative to the root and offset by their position in the child array of their parent.  Should they rather been drawn relative to their parent position ? 
Or is that the intended behavior ? Anyway you can merge the pull request if you are ok with the clean-ups.

**Pull request merged**
